### PR TITLE
Student and Company commands: change duplicate criteria

### LINKED ISSUE #126: Company command duplicate detection bug-different industry
Describe the bug:
When trying to add a company named `NTU` under the industry `Technology` with the same particulars of a `NTU` company previously added in AdmiNUS (where the only difference is in the `Industry`), it is detected as a duplicate, and the user is unable to add the company.
It is also detected as a duplicate if the other particulars are changed except for the name, which indicates the name value being used to detect duplicates.

Steps to reproduce:

1. Open the app and type company in the text box, and copy the `NTU` example (found in the invalid company command format message).
2. Paste and enter the company command example obtained in the text box, but change from `n/NTU i/University` to `n/NTU i/Technology` .

Expected behavior:
The company is added to the list.

Actual behavior:
The company is detected as a duplicate.

Screenshot:
image

### LINKED ISSUE #138: Student command should detect duplicates by same student ID instead of same name
### Description
Suggestion for Improvement: Student command should detect duplicates by same student ID instead of same name. Currently, student command detects duplicate names. Besides, the duplicate detection functionality can be stated in the UG.

### Screenshot
image

### PR DESCRIPTION
**Pull request by ruiming97**
Student duplicates are now handled by Student ID instead of Name, and Company duplicates are now determined by both Industry and Name. This enhances data integrity by ensuring unique identification for students and companies.

Let's improve the uniqueness handling to better support contact management requirements.

Fix #138 Fix #126

### CODE REVIEW

File: src/main/java/seedu/address/model/person/company/Company.java [hunk 1]
```diff
@@ -54,6 +54,25 @@ public StudentId getStudentId() {
...
+        if (otherPerson instanceof Company) {
+            return otherPerson != null
+                    && otherPerson.getName().equals(getName())
+                    && otherPerson.getIndustry().equals(getIndustry());
+        }
+
+        return false;
+    }
+
     @Override
```
Comment (JiaYi-Gallium369) [inline src/main/java/seedu/address/model/person/company/Company.java:76]: Good update for refining the uniqueness in `isSamePerson()`. We might need to check the handling of companies with industry null values

File: src/main/java/seedu/address/model/person/student/Student.java [hunk 2]
```diff
@@ -51,12 +51,21 @@ public Industry getIndustry() {
...
+        }
 
-    public int getAttendance() {
-        return attendance;
+        if (otherPerson instanceof Student) {
+            return otherPerson != null
+                    && otherPerson.getStudentId().equals(getStudentId());
+        }
+        return false;
     }
```
Comment (JiaYi-Gallium369) [inline src/main/java/seedu/address/model/person/student/Student.java:69]: Thanks for enforcing student uniqueness by Student ID. We will need to update student ID as the primary identifier to the UG
